PATCH http://localhost:8000/invoices/xpto1234 HTTP/1.1
Content-Type: application/json

{
	"creditCardHash" : "xpto1234", // Obrigatório se pix for false
	"pix": false	// Opcional, se não for enviado também é interpretado como false
}