POST https://the-starter.koud.dev/invoices HTTP/1.1
Content-Type: application/json

{
	"customer" : {
		"name": "Tester Aprovado",
		"email" : "tester@mail.com",
		"document" : "34960826312"
	},
	"product" : {
		"sku" : "xpto1234",
		"name" : "Product XPTO",
		"price" : 1.23
	}
}